### ISSUE TITLE
No metrics once CF11 updates installed

### ISSUE THREAD

**Issue by bigkevuk** [kacperus/cf-metrics#4]
Great work on this.

I've managed to compile and get it running in a clean CF11 install but sadly doesn't work once any updates are installed.

I see the message that code coverage has started but nothing in the viewer

**Comment by kacperus** [comment]
Have you cleared "Template Cache" of your CF server after deploying the patch JAR and restarting? If not that may be the reason why you don't see any classes in the statistics viewer.

If that doesn't help please let me know if you're using standalone or EAR version of the ColdFusion server. What is the JAVA version you're using? Do you have any other JARs inside "/lib/updates"?

**Comment by bigkevuk** [comment]
I'm using standalone, there are no other files in the update folder other than the patch and hotfix.

I've cleared the generated class files.

I don't get the server.log message until I hit the page to view statistics which indicates that the jar isn't being loaded on server start up

**Comment by bigkevuk** [comment]
I'm attaching versions of the .class files with and without the patch.

[cflogin_withPatch.txt](https://github.com/kacperus/cf-metrics/files/34802/cflogin_withPatch.txt)
[cflogin_withoutPatch.txt](https://github.com/kacperus/cf-metrics/files/34801/cflogin_withoutPatch.txt)

**Comment by kacperus** [comment]
I can see that the "cflogin_withPatch.class" contains necessary modifications which indicates that "cf-metrics" patch got applied to ColdFusion engine. Strange thing you can't see any statistics via the viewer...

The viewer uses the same singleton instance of a collector which is used to gather statistics from template execution. If nothing is shown in the viewer it may indicate it references other instance. That's weird and my only guess is that some other ClassLoader was used for engine and other for templates.

Are you absolutely sure that the cf-metrics patch JAR is only present in the "/lib/updates" directory? Sorry for this question but I'm trying to figure out what potentially may be wrong without.

PS. Are you seriously using Java 1.3? :) At least is what class's major-minor version indicates.

**Comment by bigkevuk** [comment]
Thanks for your help with this, I've managed to get it working with HF0002 but not with anything after HF0003 when Java 8 support was added (Maybe a red herring)

I'm using the ColdFusion Express install (Quickest way to get it running) I'm running on OSX and I'm certainly not using Java 1.3 :)

I've zipped up the install from the root of my hard drive with installs with:
- Not Patch - No Hot Fix 
- Patch  - No Hot Fix - Works
- Patch - Hot Fix 0002 - Works
- Patch - Hot Fix 0006 - Doesn't Work

https://dl.dropboxusercontent.com/u/65527/ColdFusion.zip 

All instances use port 8500 and can be started by the bin/cfstart.sh 

Each have the same setup:
- http://localhost:8500/email/login.cfm (The old CF4.5 sample CrazyCab Application)
- http://localhost:8500/cfmetrics/coverage-statistics.cfm

Not sure if there is anything else I can look for.

Do you have it running on CF11 with HF6?

**Comment by kacperus** [comment]
The zip file seems to be corrupted or it got corrupted while I was downloading it but it's not a problem as I have managed to "replicate" the issue on my CF11 instance as well after Adobe CF HF6 was applied. I confirm it does not work with it :(

This is because the HF6 (and most probably it started with HF4) updates core classes of the ColdFusion engine among which are those which I've also woven with aspects. This is an interesting case and may require adding HF6 JAR to the classpath of the cf-metrics project so that the HF6 not the original engine classes got modified. This should help if those classes hasn't changed in a great manner.

Another thing it is the alphabetic order in which update JARs are applied by CF. I'm not yet sure but the cf-metrics update JAR may need to be renamed as well. This is something I have to check.

I'll keep you updated.

**Comment by bigkevuk** [comment]
Thanks Pal,

I do have access to the engineering team, I would like to get them to add this functionality to CF12 as if you've been able to do it without access to the source code I'm sure it would be very easy for them to add and hope it would just be a JVM parameter to enable it. 

To this end would you mind if I suggested this to them, I'll also ask if I can get some of their resource to get this fixed for CF11 :)

Cheers

**Comment by kacperus** [comment]
Do you mean Adobe engineering team? If they would include "code coverage" into their product that would mean... the end of my project. :') Just kidding. It's the right thing to do! I would be super happy to so a code coverage as a feature in CF server.

Frankly speaking this should have been done by the Adobe long time ago!

PS. With a bit of luck it may also work with CF12 just like it work for the previous releases. Same codebase on my end, same aspects which seem to fit multiple versions.

**Comment by bigkevuk** [comment]
I'll ping them and see if we can get this sorted :-) This feature is a long time coming and needs to be there ASAP

**Comment by bardware** [comment]
I didn't know how to enable debug, so I added a couple `log.info` calls to the code and recompiled. I'm on CF 11 Updater 6 on Windows using JAVA 8 64 bit.
It seems `preparePageCoverage` is not being called by the aspect as it should be. Thus the `pages` HashSet stays empty all the time.

**Comment by kacperus** [comment]
Thanks @bardware for your investigation. That is the reason why statistics are not being recorded, indeed. The problem is that CF11 Hot Fix 4 (or higher) introduces so many changes to the core classes of CF engine (something must have been really bad there!) that classes instrumented with my aspects no longer work as expected.

The idea is to instrument both core and patch JAR classes in order to produce instrumented HF which would have to be used instead of original JAR. I would provide both code coverage and fixes.

I'm currently trying do develop such a script with a help of maven and ant task. Unfortunately I don't have much time these days, so any help is more than welcome!

**Comment by rcastagno** [comment]
I've been able to hack together a version of this working with cf2018 + hf11
I've done something like this:
- use hfxxx.jar instead of cfusion.jar
- place the content of generated patch INTO the existing coldfusion hfxxx.jar
- restart

This way I've been able to get the stats. 

Doing it with the project as-is, I got weird errors caused by CF not loading hfxxx.jar but just the newly patched jar, because it is loading just the LATEST jar in the updates folder.

Also, this process may trigger all sorts of "Branch offset too large for short" errors at runtime, because it's instrumenting classes, thus lengthening methods.

**Comment by kacperus** [comment]
Hey @rcastagno, thanks for sharing the steps you've taken. I'm curious to know if the hf11 for cf2018 contains all necessary files which are to be "adjusted" by aspects. Have you checked it?

When it comes to increasing the Java method byte code, you're right. It will generate problems like this. I remember some crazy long methods written in CF in my previous company code base which caused such problems after cf-metrics were enabled. The solution was to rewrite them :)

**Comment by rcastagno** [comment]
"I'm curious to know if the hf11 for cf2018 contains all necessary files which are to be "adjusted" by aspects. Have you checked it?" 

Nope, just smashed pieces together until they worked! :)

But since they worked, I'll probably look a bit deeper in the next few weeks/months. 

If all goes well I'll try to contribute back
